import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] }); // cambiar fuente

export const metadata = {
  title: "Dakota Next App",
  description: "Generated by Dakota Next App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
